//-------------------

USE FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS;
SELECT * FROM COVID_19_INDONESIA_SIDHARTH_PANDA
LIMIT 10;

//-------------------
USE INTERVIEW_DB;
CREATE SCHEMA IF NOT EXISTS PLAYGROUND_SIDHARTH_PANDA;

USE INTERVIEW_DB.PLAYGROUND_SIDHARTH_PANDA;
CREATE TABLE IF NOT EXISTS TABLE_1(Id INT);
DROP TABLE TABLE_1;