
CREATE TRANSIENT TABLE IF NOT EXISTS COVID_BY_PROVIENCE AS
SELECT  
    COUNTRY,
    LOCATION,
    LOCATION_ISO_CODE,
    DATE,
    POPULATION_DENSITY,
    POPULATION,
    GROWTH_FACTOR_OF_NEW_CASES,
    GROWTH_FACTOR_OF_NEW_DEATHS
FROM REQ_COLS;