CREATE TRANSIENT TABLE IF NOT EXISTS COVID_BY_DATE AS 
SELECT
    COUNTRY,
    LOCATION,
    LOCATION_ISO_CODE,
    DATE,
    COALESCE(NEW_RECOVERED,0) AS NEW_RECOVERED,
    COALESCE(TOTAL_RECOVERED,0) AS TOTAL_RECOVERED,
    COALESCE(NEW_ACTIVE_CASES,0) AS NEW_ACTIVE_CASES,
    COALESCE(TOTAL_ACTIVE_CASES,0) AS TOTAL_ACTIVE_CASES,
    COALESCE(NEW_DEATHS,0) AS NEW_DEATHS,
    COALESCE(TOTAL_DEATHS,0) AS TOTAL_DEATHS,
    COALESCE(TOTAL_CASES,0) AS TOTAL_CASES,
    COALESCE(CASE_RECOVERED_RATE, 0.00) AS CASE_RECOVERED_RATE,
    COALESCE(TOTAL_DEATHS_PER_MILLION, 0.00) AS TOTAL_DEATHS_PER_MILLION,
    COALESCE(GROWTH_FACTOR_OF_NEW_CASES, 0.00) AS GROWTH_FACTOR_OF_NEW_CASES
FROM REQ_COLS;
